module.exports = {
  bad: [
    [
      "Pressured",
      "Scared",
      "Defensive",
      "Worried",
      "Worthless",
      "Stupid",
      "Disrespected",
      "Excluded",
      "Threatened",
      "Nervous",
      "Misunderstood",
    ],
    [
      "Depressed",
      "Lonely",
      "Abandoned",
      "Unimportant",
      "Hopeless",
      "Guilty",
      "Ashamed",
      "Disappointed",
      "Embarrassed",
      "Ugly",
      "Small",
    ],
    [
      "Angry",
      "Let down",
      "Humiliated",
      "Betrayed",
      "Jealous",
      "Frustrated",
      "Annoyed",
      "Disgust",
      "Contempt",
    ],
    ["Bored", "Stressed", "Tired", "Overwhelmed"],
    ["Surprised", "Confused", "Bullied", "Down", "Unloved"],
  ],
  good: [
    [
      "Curious",
      "Confident",
      "Courageous",
      "Loving",
      "Inspired",
      "Brave",
      "Joy",
      "Proud",
      "Respected",
      "Peaceful",
      "Optimistic",
      "Playful",
      "Thankful",
    ],
  ],
};
